### PR TITLE
addition of real preset list

### PR DESCRIPTION
**Pull request by switowski**
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>

### CODE REVIEW

**Comment by switowski** [comment]
I have updated the list of presets and also changed it's structure to a more suitable one.
Tests will fail but we have to change how the start encoding works, since for each aspect ratio we will always generate ALL the slaves, not only one. So adding a new video should start all the encoding jobs for a given aspect ration (which in most cases means 5 jobs).
Still new confirmation from Marek about one missing preset that is supposed to be there.

**Comment by switowski** [comment]
No more WiP, `start encoding` now requires the `preset_id`

**Comment by egabancho** [comment]
Before merging this one, could you also make a PR to update https://github.com/CERNDocumentServer/cds/blob/cdslabs_qa/cds/modules/webhooks/tasks.py#L283 ?

**Comment by switowski** [comment]
@drjova ready to be merged, the PR for cds will follow up shortly

**Comment by egabancho** [comment]
we should wait until the CDS PR is ready, otherwise all tests will fail 😉

**Pull request merged**
