### PR TITLE
release: 0.1.0

### PR DESCRIPTION
**Pull request by hachreak**
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by hachreak** [comment]
ping @drjova (I don't have right to add reviewers or anything else... :smile: )

**Comment by hachreak** [comment]
ping @drjova :shipit: (could you add the `project` at least? :smile: )

**Comment by drjova** [comment]
@hachreak you should have access now :) I'm waiting for pypi confirmation email because I created an account for releasing CDS packages, we don't have one right now [.travis.yml](https://github.com/CERNDocumentServer/cds-sorenson/blob/master/.travis.yml)

**Comment by hachreak** [comment]
:+1:

**Pull request merged**
